name: build_werkkzeug3

on:
  push:
    branches: [ "master", "trace" ]
  pull_request:
    branches: [ "master", "trace" ]
  workflow_dispatch: # Позволяет запускать сборку кнопкой в интерфейсе

env:
  SOLUTION_FILE_PATH: werkkzeug3_kkrieger/wz3projects.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Base Console (Required Dependency)
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild 'werkkzeug3_kkrieger/base_console/base_console.vcxproj' /p:Configuration=Release /p:Platform=Win32

      - name: Build Werkkzeug Solution
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=Release /p:Platform=x86 /p:BuildProjectReferences=true

      - name: Build GenThree
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild 'genthree/genthree.sln' /p:Configuration=Release /p:Platform=Win32

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kkrieger-Werkkzeug-Binaries
          path: |
            **/*.exe
            !obj/**
          if-no-files-found: error
