name: build_werkkzeug3

on:
  push:
    branches: [ "master", "trace" ]
  pull_request:
    branches: [ "master", "trace" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: werkkzeug3_kkrieger/wz3projects.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Обновлено до v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2 # Обновлено до v2

      - name: Install DirectX SDK (June 2010)
        shell: powershell
        run: |
          # Установка DirectX SDK через Chocolatey для получения dinput.lib
          choco install directx-sdk -y
          echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)" >> $env:GITHUB_ENV

      - name: Build Base Console
        shell: powershell
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;"
          $env:INCLUDE = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include;" + $env:INCLUDE
          $env:LIB = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86;" + $env:LIB
          msbuild 'werkkzeug3_kkrieger/base_console/base_console.vcxproj' /p:Configuration=Release /p:Platform=Win32 /p:RuntimeLibrary=MultiThreaded

      - name: Build Werkkzeug Solution
        shell: powershell
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;"
          $env:INCLUDE = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include;" + $env:INCLUDE
          $env:LIB = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86;" + $env:LIB
          
          msbuild ${{ env.SOLUTION_FILE_PATH }} `
            /p:Configuration=Release `
            /p:Platform=x86 `
            /p:BuildProjectReferences=true `
            /p:RuntimeLibrary=MultiThreaded `
            /p:ForceImportBeforeCppTargets="$($pwd.Path)\fix.props"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # Обновлено до v4 (исправляет ошибку со скриншота)
        with:
          name: Kkrieger-Binaries
          path: |
            **/*.exe
            !obj/**
          if-no-files-found: warn
