- name: Build Base Console
        shell: powershell
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;"
          $dxInclude = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include"
          $dxLib = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86"
          
          msbuild 'werkkzeug3_kkrieger/base_console/base_console.vcxproj' `
            /p:Configuration=Release /p:Platform=Win32 `
            /p:IncludePath="$dxInclude;$(IncludePath)" `
            /p:LibraryPath="$dxLib;$(LibraryPath)"

      - name: Build Werkkzeug Solution
        shell: powershell
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;"
          $dxInclude = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include"
          $dxLib = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86"
          
          msbuild ${{ env.SOLUTION_FILE_PATH }} `
            /p:Configuration=Release `
            /p:Platform=x86 `
            /p:BuildProjectReferences=true `
            /p:ForceImportBeforeCppTargets="$($pwd.Path)\fix.props" `
            /p:IncludePath="$dxInclude;$(IncludePath)" `
            /p:LibraryPath="$dxLib;$(LibraryPath)"

      - name: Build GenThree
        shell: powershell
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;"
          $dxInclude = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include"
          $dxLib = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86"
          
          msbuild 'genthree/genthree.sln' `
            /p:Configuration=Release /p:Platform=Win32 `
            /p:IncludePath="$dxInclude;$(IncludePath)" `
            /p:LibraryPath="$dxLib;$(LibraryPath)"
